[[rules]]
    [rules.allowlist]
        files = ['''_config.yml''',
                 '''Gemfile.lock'''
                ]
[allowlist]
    files = ['''_config.yml''',
             '''Gemfile.lock'''
            ]